[phases.setup]
nixPkgs = ["nodejs-20_x", "python3", "chromium"]

[phases.setup.nixPkgsArchive]
archive = "nixpkgs-unstable"

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
